# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: suporte.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'suporte.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsuporte.proto\x12\x07suporte\"]\n\x07\x43hamado\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07\x63liente\x18\x02 \x01(\t\x12\x11\n\tdescricao\x18\x03 \x01(\t\x12\x12\n\nprioridade\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\"\x17\n\tIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty\"3\n\rListaChamados\x12\"\n\x08\x63hamados\x18\x01 \x03(\x0b\x32\x10.suporte.Chamado\"3\n\x0eStatusResponse\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x10\n\x08mensagem\x18\x02 \x01(\t2\xfe\x01\n\x0eServicoSuporte\x12\x39\n\x0c\x41\x62rirChamado\x12\x10.suporte.Chamado\x1a\x17.suporte.StatusResponse\x12\x38\n\x10\x43onsultarChamado\x12\x12.suporte.IdRequest\x1a\x10.suporte.Chamado\x12\x38\n\x0eListarChamados\x12\x0e.suporte.Empty\x1a\x16.suporte.ListaChamados\x12=\n\x10\x41tualizarChamado\x12\x10.suporte.Chamado\x1a\x17.suporte.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'suporte_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHAMADO']._serialized_start=26
  _globals['_CHAMADO']._serialized_end=119
  _globals['_IDREQUEST']._serialized_start=121
  _globals['_IDREQUEST']._serialized_end=144
  _globals['_EMPTY']._serialized_start=146
  _globals['_EMPTY']._serialized_end=153
  _globals['_LISTACHAMADOS']._serialized_start=155
  _globals['_LISTACHAMADOS']._serialized_end=206
  _globals['_STATUSRESPONSE']._serialized_start=208
  _globals['_STATUSRESPONSE']._serialized_end=259
  _globals['_SERVICOSUPORTE']._serialized_start=262
  _globals['_SERVICOSUPORTE']._serialized_end=516
# @@protoc_insertion_point(module_scope)
